import ReactFlow, {
  Background,
  Controls,
} from "reactflow";

import "reactflow/dist/style.css";

import { useIncident } from "../context/IncidentContext";

export default function DigitalTwin() {
  const {
    incidentData,
    analysisData,
    digitalTwinData,
  } = useIncident();

  if (!digitalTwinData) {
    return (
      <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">
        <h1 className="text-3xl">
          No Digital Twin Data Found
        </h1>
      </div>
    );
  }

  const getNodeStyle = (status) => {
    if (status === "critical") {
      return {
        background: "#7f1d1d",
        color: "white",
        border: "2px solid red",
        boxShadow: "0 0 20px rgba(255,0,0,0.7)",
      };
    }

    if (status === "warning") {
      return {
        background: "#78350f",
        color: "white",
        border: "2px solid orange",
      };
    }

    return {
      background: "#14532d",
      color: "white",
      border: "2px solid #22c55e",
    };
  };

  const nodes =
    digitalTwinData.routeStations.map(
      (station, index) => ({
        id: String(index + 1),

        position: {
          x: index * 250,
          y: 100,
        },

        data: {
          label: station.name,
        },

        style: getNodeStyle(
          station.status
        ),
      })
    );

  const edges =
    digitalTwinData.routeStations
      .slice(0, -1)
      .map((_, index) => ({
        id: `e${index + 1}-${index + 2}`,
        source: String(index + 1),
        target: String(index + 2),
        animated: true,
      }));

  return (
    <div className="min-h-screen bg-slate-950 text-white">

      <div className="border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-6 py-5">

          <h1 className="text-3xl font-bold text-cyan-400">
            AI Generated Digital Twin
          </h1>

          <p className="text-slate-400 mt-2">
            Dynamic railway route generated by AI.
          </p>

        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 pt-6">

        <div className="grid md:grid-cols-4 gap-6">

          <div className="bg-slate-900 p-5 rounded-2xl">
            <p className="text-slate-400">
              Affected Station
            </p>

            <h2 className="text-xl font-bold text-red-400">
              {digitalTwinData.affectedStation}
            </h2>
          </div>

          <div className="bg-slate-900 p-5 rounded-2xl">
            <p className="text-slate-400">
              Impact Radius
            </p>

            <h2 className="text-xl font-bold">
              {digitalTwinData.impactRadius}
            </h2>
          </div>

          <div className="bg-slate-900 p-5 rounded-2xl">
            <p className="text-slate-400">
              Routes Impacted
            </p>

            <h2 className="text-xl font-bold">
              {digitalTwinData.estimatedAffectedRoutes}
            </h2>
          </div>

          <div className="bg-slate-900 p-5 rounded-2xl">
            <p className="text-slate-400">
              Severity
            </p>

            <h2 className="text-xl font-bold text-red-400">
              {analysisData?.severity}
            </h2>
          </div>

        </div>

      </div>

      <div className="h-[60vh] mt-8">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          fitView
        >
          <Background />
          <Controls />
        </ReactFlow>
      </div>

    </div>
  );
}